# Generated by Django 5.2.11 on 2026-02-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='customers.cliente', verbose_name='Cliente'),
        ),
    ]
