# Generated by Django 5.2.11 on 2026-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_sales_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco/Transferencia')], default='efectivo', max_length=20, verbose_name='Forma de Pago'),
        ),
    ]
