# Generated by Django 5.2.11 on 2026-02-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_sales_forma_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesitems",
            name="qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
