# Generated by Django 5.0.6 on 2026-10-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_borrado_logico_productos"),
        ("pos", "0005_sales_vendedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesitems",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.products"
            ),
        ),
    ]
