# Generated by Django 5.2.11 on 2026-02-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_purchaseproduct_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('banco', 'Banco/Transferencia')], default='efectivo', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pagado',
            field=models.BooleanField(default=False, help_text='Indica si la compra ya fue pagada', verbose_name='Pagado'),
        ),
    ]
