# Generated by Django 5.2.14 on 2026-05-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0003_purchase_fecha_pago_purchase_forma_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="iva_monto",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="IVA"
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="perc_monto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Percepción IVA",
            ),
        ),
    ]
