# Generated by Django 5.2.14 on 2026-05-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_purchase_iva_monto_purchase_perc_monto"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="subtotal_productos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=18,
                verbose_name="Subtotal sin impuestos",
            ),
        ),
    ]
