# Generated by Django 5.2.14 on 2026-05-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_purchase_subtotal_productos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproduct",
            name="qty",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
