# Generated by Django 5.2.14 on 2026-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0006_alter_purchaseproduct_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproduct",
            name="qty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
