# Generated by Django 5.0.6 on 2026-10-02
#
# 1) Agrega PurchaseProduct.costo_neto = costo de la factura, sin IVA ni percepcion.
# 2) Lo completa para las compras que ya existen.
#
# En las compras viejas solo se guardo el costo FINAL (con el impuesto repartido adentro).
# El costo de factura se recupera deshaciendo esa cuenta:
#       costo final = costo de factura * (subtotal + impuestos) / subtotal
#   =>  costo de factura = costo final * subtotal / (subtotal + impuestos)

from decimal import Decimal

from django.db import migrations, models


def costo_neto_historico(costo_final, qty_x_costo_total, subtotal_guardado, impuestos):
    """
    Devuelve el costo de factura de un renglon viejo.

    costo_final        : costo guardado en el renglon (con impuestos adentro)
    qty_x_costo_total  : suma de costo_final * cantidad de todos los renglones de la compra
    subtotal_guardado  : Purchase.subtotal_productos
    impuestos          : IVA + percepcion de la compra
    """
    if impuestos <= 0 or qty_x_costo_total <= impuestos:
        # Compra sin impuestos (o datos raros): el costo final ES el de factura.
        return costo_final

    # Caso normal: el subtotal guardado + impuestos coincide con lo que suman los renglones.
    if subtotal_guardado > 0 and abs(subtotal_guardado + impuestos - qty_x_costo_total) <= Decimal('1'):
        factor = subtotal_guardado / (subtotal_guardado + impuestos)
        return (costo_final * factor).quantize(Decimal('0.0001'))

    # Compra que fue editada con la pantalla vieja (el subtotal quedo desactualizado):
    # se usa lo que suman los renglones. Es una aproximacion, se redondea a centavos.
    factor = (qty_x_costo_total - impuestos) / qty_x_costo_total
    return (costo_final * factor).quantize(Decimal('0.01'))


def completar_costo_neto(apps, schema_editor):
    Purchase = apps.get_model('purchase', 'Purchase')
    PurchaseProduct = apps.get_model('purchase', 'PurchaseProduct')

    for compra in Purchase.objects.all():
        items = list(PurchaseProduct.objects.filter(purchase=compra))
        if not items:
            continue
        total_renglones = sum((it.cost * it.qty for it in items), Decimal('0'))
        impuestos = (compra.iva_monto or Decimal('0')) + (compra.perc_monto or Decimal('0'))
        for it in items:
            it.costo_neto = costo_neto_historico(it.cost, total_renglones, compra.subtotal_productos or Decimal('0'), impuestos)
        PurchaseProduct.objects.bulk_update(items, ['costo_neto'])

    # Renglones sueltos, sin compra (datos muy viejos): costo de factura = costo final.
    for it in PurchaseProduct.objects.filter(purchase__isnull=True, costo_neto__isnull=True):
        it.costo_neto = it.cost
        it.save(update_fields=['costo_neto'])


def no_hacer_nada(apps, schema_editor):
    """Para poder volver atras la migracion: el campo se borra solo."""


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0007_alter_purchaseproduct_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseproduct",
            name="costo_neto",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=18,
                null=True,
                verbose_name="Costo de factura (sin impuestos)",
            ),
        ),
        migrations.RunPython(completar_costo_neto, no_hacer_nada),
    ]
