# Generated by Django 5.0.6 on 2026-10-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_borrado_logico_productos"),
        ("purchase", "0008_costo_neto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseproduct",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.products",
            ),
        ),
    ]
