# Generated by Django 5.2.14 on 2026-05-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("facturado", "Facturado"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendiente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
