# Generated by Django 5.2.11 on 2026-02-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del cliente', max_length=200, verbose_name='Nombre Completo')),
                ('dni', models.CharField(help_text='Documento de identidad único', max_length=20, unique=True, verbose_name='DNI/CUIT')),
                ('phone', models.CharField(blank=True, help_text='Número de contacto', max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, help_text='Dirección completa del cliente', null=True, verbose_name='Dirección')),
                ('tipo_cliente', models.CharField(choices=[('minorista', 'Minorista'), ('mayorista', 'Mayorista')], default='minorista', help_text='Define la lista de precios a aplicar', max_length=20, verbose_name='Tipo de Cliente')),
                ('activo', models.BooleanField(default=True, help_text='Cliente activo en el sistema', verbose_name='Activo')),
                ('notas', models.TextField(blank=True, help_text='Observaciones o comentarios sobre el cliente', null=True, verbose_name='Notas')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['dni'], name='customers_c_dni_986670_idx'), models.Index(fields=['name'], name='customers_c_name_d34c17_idx'), models.Index(fields=['activo'], name='customers_c_activo_0118d1_idx')],
            },
        ),
    ]
