# Generated by Django 6.0.2 on 2026-05-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("pos", "0004_alter_salesitems_qty"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoCuentaCorriente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("venta", "Venta"), ("pago", "Pago")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Monto"
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Forma de Pago",
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_cuenta",
                        to="customers.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimiento_cuenta",
                        to="pos.sales",
                        verbose_name="Venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Cuenta Corriente",
                "verbose_name_plural": "Movimientos Cuenta Corriente",
                "ordering": ["-fecha"],
            },
        ),
    ]
