# Generated by Django 5.2.11 on 2026-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="marca",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Marca"
            ),
        ),
    ]
