# Generated by Django 6.0.2 on 2026-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_products_marca"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="punto_pedido",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Avisar cuando el stock llegue a este valor (0 = sin alerta)",
                max_digits=10,
                verbose_name="Punto de Pedido",
            ),
        ),
    ]
