# Generated by Django 5.2.14 on 2026-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_products_punto_pedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="codigo_barras",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Código de Barras",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="codigo_tipo",
            field=models.CharField(
                choices=[
                    ("externo", "Externo (fabricante)"),
                    ("interno", "Interno (generado)"),
                ],
                default="interno",
                help_text="Externo: viene del fabricante. Interno: generado por el sistema.",
                max_length=10,
                verbose_name="Tipo de Código",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="tipo_venta",
            field=models.CharField(
                choices=[("unidad", "Unidad"), ("fraccionable", "Fraccionable")],
                default="unidad",
                help_text="Unidad: agrega 1 al escanear. Fraccionable: pide cantidad.",
                max_length=20,
                verbose_name="Tipo de Venta",
            ),
        ),
    ]
