# Generated by Django 5.2.14 on 2026-05-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_products_codigo_barras_products_codigo_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
