# Generated by Django 5.2.14 on 2026-05-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_products_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
