# Generated by Django 5.2.14 on 2026-05-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_products_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="plu",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número PLU para balanza (asignado automáticamente al marcar como fraccionable)",
                null=True,
                unique=True,
                verbose_name="PLU",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="producto_origen",
            field=models.ForeignKey(
                blank=True,
                help_text="Para fraccionables: producto del cual proviene (actualiza costo automáticamente)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fraccionados",
                to="inventory.products",
                verbose_name="Producto Origen",
            ),
        ),
    ]
