# Generated by Django 6.0.7 on 2026-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_products_plu_products_producto_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='codigo_tipo',
            field=models.CharField(choices=[('externo', 'Externo (fabricante)'), ('interno', 'Interno (generado)')], default='externo', help_text='Externo: viene del fabricante. Interno: generado por el sistema.', max_length=10, verbose_name='Tipo de Código'),
        ),
    ]
