# Generated by Django 5.0.6 on 2026-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_products_codigo_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="eliminado",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Oculto en todo el sistema. Se conserva solo para el historial de ventas y compras.",
                verbose_name="Eliminado",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="fecha_eliminado",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de eliminación"
            ),
        ),
    ]
