# Generated by Django 5.0.6 on 2026-10-02 18:15
#
# 1) Crea las tablas del conteo de stock (ConteoStock y sus renglones).
# 2) Recalcula el estado Activo/Inactivo de los productos con la regla nueva:
#       Activo = tiene costo y precio.  El stock ya no interviene.
#    (Antes un producto por unidad con stock 0 quedaba Inactivo y no se podia vender.)

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def recalcular_estado(apps, schema_editor):
    Products = apps.get_model('inventory', 'Products')
    vendibles = Products.objects.filter(eliminado=False, cost__gt=0, precio_minorista__gt=0)
    vendibles.exclude(status=1).update(status=1)
    Products.objects.filter(eliminado=False).exclude(pk__in=vendibles.values('pk')).exclude(status=0).update(status=0)


def no_hacer_nada(apps, schema_editor):
    """Para poder volver atras la migracion: el estado se recalcula solo al guardar cada producto."""


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_borrado_logico_productos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConteoStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("nota", models.CharField(blank=True, default="", max_length=200)),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iniciado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteo de stock",
                "verbose_name_plural": "Conteos de stock",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ConteoStockRenglon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_sistema",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Stock que decía el sistema",
                    ),
                ),
                (
                    "contado",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Contado"
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "automatico",
                    models.BooleanField(
                        default=False,
                        verbose_name="Puesto en cero al cerrar (no se contó)",
                    ),
                ),
                (
                    "conteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renglones",
                        to="inventory.conteostock",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conteos",
                        to="inventory.products",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Renglón de conteo",
                "verbose_name_plural": "Renglones de conteo",
                "ordering": ["product__name"],
                "unique_together": {("conteo", "product")},
            },
        ),
        migrations.RunPython(recalcular_estado, no_hacer_nada),
    ]
