# Generated by Django 5.2.11 on 2026-02-12 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0003_sales_forma_pago'),
        ('purchase', '0003_purchase_fecha_pago_purchase_forma_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo en Efectivo (Caja)')),
                ('saldo_banco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo en Banco')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Caja',
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha del Cierre')),
                ('saldo_inicial_efectivo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial en Efectivo')),
                ('saldo_inicial_banco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Inicial en Banco')),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas en Efectivo')),
                ('total_ventas_banco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ventas con Banco')),
                ('total_compras_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Compras en Efectivo')),
                ('total_compras_banco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Compras con Banco')),
                ('total_retiros_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retiros de Efectivo')),
                ('total_retiros_banco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Retiros de Banco')),
                ('total_gastos_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos en Efectivo')),
                ('total_gastos_banco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos con Banco')),
                ('total_transferencias_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transferencias Caja → Banco')),
                ('total_transferencias_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Transferencias Banco → Caja')),
                ('saldo_esperado_efectivo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Esperado en Efectivo')),
                ('saldo_esperado_banco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Esperado en Banco')),
                ('saldo_real_efectivo', models.DecimalField(decimal_places=2, help_text='Efectivo físicamente contado en caja', max_digits=12, verbose_name='Saldo Real Contado en Efectivo')),
                ('diferencia_efectivo', models.DecimalField(decimal_places=2, help_text='Positivo = Sobrante, Negativo = Faltante', max_digits=12, verbose_name='Diferencia en Efectivo')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el cierre', verbose_name='Notas del Cierre')),
                ('fecha_hora_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Cierre')),
                ('cerrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta_efectivo', '💵 Venta en Efectivo'), ('venta_banco', '🏦 Venta con Banco/Transferencia'), ('compra_efectivo', '🛒 Pago de Compra en Efectivo'), ('compra_banco', '💳 Pago de Compra con Banco'), ('transferencia_caja_banco', '📤 Depósito (Caja → Banco)'), ('transferencia_banco_caja', '📥 Retiro Banco (Banco → Caja)'), ('retiro_efectivo', '💸 Retiro de Caja'), ('retiro_banco', '🏧 Retiro de Banco'), ('gasto', '📝 Gasto/Egreso'), ('ajuste_efectivo', '⚙️ Ajuste Manual Efectivo'), ('ajuste_banco', '⚙️ Ajuste Manual Banco'), ('inicial_efectivo', '🔵 Saldo Inicial Efectivo'), ('inicial_banco', '🔵 Saldo Inicial Banco')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('concepto', models.TextField(help_text='Descripción del movimiento', verbose_name='Concepto/Descripción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('afecta_efectivo', models.BooleanField(default=False, verbose_name='Afecta Efectivo')),
                ('afecta_banco', models.BooleanField(default=False, verbose_name='Afecta Banco')),
                ('es_ingreso', models.BooleanField(default=True, help_text='True = Ingreso (+), False = Egreso (-)', verbose_name='Es Ingreso')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='purchase.purchase', verbose_name='Compra Asociada')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='pos.sales', verbose_name='Venta Asociada')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo'], name='finances_mo_tipo_fe25a3_idx'), models.Index(fields=['fecha'], name='finances_mo_fecha_c1c8df_idx'), models.Index(fields=['-fecha'], name='finances_mo_fecha_7eb83d_idx')],
            },
        ),
    ]
